/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.env.example --include-runtime=false partykit/worker-configuration.d.ts` (hash: 44c1e95714730e616e61cb46b41e9e2b)
interface __BaseEnv_Env {
	DATABASE_URL: string;
	CREATIVE_FEEDS: string;
	INGEST_CRON_SECRET: string;
	GEMINI_API_KEY: string;
	GEMINI_MODEL: string;
	GALLERY_ROOM: DurableObjectNamespace<import("./index").GalleryRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GalleryRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "CREATIVE_FEEDS" | "INGEST_CRON_SECRET" | "GEMINI_API_KEY" | "GEMINI_MODEL">> {}
}
